### ISSUE TITLE
HSV support

### ISSUE THREAD

**Issue by archiif** [neeasade/color-tools.el#3]
Will HSV be supported?

**Comment by neeasade** [comment]
I see color.el has `color-rgb-to-hsv`, so sure, shouldn't be difficult to add. I'll aim to have the same interface as the other functions (hue 0 to 360, SV 0 to 100)

**Comment by neeasade** [comment]
color.el doesn't ship with an `hsv-to-rgb`, so I'll implement the one outlines from http://peteroupc.github.io/colorgen.html

**Comment by neeasade** [comment]
Added - Tested against http://colorizer.org/

**Comment by archiif** [comment]
Thanks!
